### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by comleoita** [Leone25/kitaboo-downloader#3]
Ciao,
Sono sempre io, non voleo ri-romperti le pelotas ma purtroppo devo.
Adesso, dopo bsmart, sto convertendo kitaboo solo che mi da questo errore:

`Processing...
Downloading 1/211
ink_file_open: 'C:\Users\Leonardo Compagnoni\Desktop\kitaboo-downloader-main\temp\page0001.svg' cannot be opened!
InkscapeApplication::document_open: Failed to open: C:\Users\Leonardo Compagnoni\Desktop\kitaboo-downloader-main\temp\page0001.svg
ConcreteInkscapeApplication::on_open: failed to create document!

(node:12512) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './temp/page0001.pdf'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at C:\Users\Leonardo Compagnoni\Desktop\kitaboo-downloader-main\index.js:26:48
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

poi non sono sicuro dei cookie che ho copiato perchè hanno un aspetto simile a questo:
`kitaboo_metadata_chain_0=1f8b0800000000000000333530b530b7d001009396703b07000000; kitaboo_metadata=7b5e2012e4832c150fcce97faa02fb70fbaed892c8b4be3cf7b66850f73c740467311db4069431da80756183f149b3022eb45e78b893d6cc0d3bc175508c9dff999074337ede144f32e52047763b15a4ec2e7a70cc2eb739f07e13e3e4548f586ce8910e6ac03e018b46baebe06bca0bfcfd9a3d4c63431fccd6e63bb3d21d6b9c71bc424bfd80766e65667c0fee0045f58ef03e5c39becd57fba026d36248ea3fc1289b8288f5e9eb21b9df304fb484e312204b1c490b841ae49d4a402d90189e806742d67273b6ec4aba8e5ac5a8…it"]; _ga_FL8QBN8HHQ=GS1.1.1633805623.3.1.1633805656.0; _ga=GA1.1.965150192.1633800160; _gid=GA1.2.1995142432.1633800160; myz_token=zlmeojnfwozm; _ga_4SVMGN1W5K=GS1.1.1633809219.3.1.1633809248.0; AWSALB=0XkezmCqzbm5cxvdf6HaQPEhKS/8oewFBzGplwN658RQsaeq0G5CRiC3WGDq2wNgmi+wiYne5trLXgkYOibcZf/LbHPJJKt6NiCbh2pCZyRkIBbkbN3aTX17U+5I; AWSALBCORS=0XkezmCqzbm5cxvdf6HaQPEhKS/8oewFBzGplwN658RQsaeq0G5CRiC3WGDq2wNgmi+wiYne5trLXgkYOibcZf/LbHPJJKt6NiCbh2pCZyRkIBbkbN3aTX17U+5I; j_sessID=a17645fb-05c6-42bb-a1c3-1468c14eab78`

**Comment by Leone25** [comment]
Eh no invece, non l'hai copiato tutto 😂

Quei 3 puntini in centro significano che è stato troncato

Per risolvere abilita la visualizzazio e degli headers in raw e seleziina i cookie in wuel modo

Devo seriamente decidermi di fare un paio di modifiche, che tra l'altro wuel cookie è pure statico . . .

**Comment by comleoita** [comment]
ahhh
quindi il problema di tutto sono i cookie che ho copiato

ricontrollo quello che mi hai detto.
poi ti faccio sapere
Grazie Ancora e Ancora

**Comment by comleoita** [comment]
TU SEI UN CAZZO DI GENIO
Ora funziona tutto
Grazie

**Comment by Leone25** [comment]
Non sono un genio, questi programmi mi hanno fatto impazzire un sacco wuindi ne ho viste di ogni 😅
